version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:5.0 # Pin to a stable version
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-secret}
    healthcheck:
      test: "exit 0" # Replace with a real check or Mongo command
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    # Optionally add resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.50"

  telegpt:
    container_name: telegpt
    command: python3 bot/bot.py
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  mongo_express:
    container_name: mongo-express
    image: mongo-express:1.0.0 # Pin to a specific version
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=telegpt
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-secret}
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://mongo-express:${MONGO_EXPRESS_PORT:-8081} || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: "0.10"

networks:
  app-network:
    driver: bridge
